# Flutter build
name: $(Rev:r)

variables:
  projectDirectory: 'covid_19_tracker'

trigger:
  - master

stages:

- stage: AndroidStage
  pool:
    vmImage: 'macos-latest'
  dependsOn: []
  displayName: Android
  jobs:

  - job: AndroidJob
    displayName: Android
    steps: 

    - task: FlutterInstall@0
      displayName: "Install Flutter SDK"
      inputs:
        mode: 'auto'
        channel: 'stable'
        customVersion: '2.10.0'

    - task: FlutterCommand@0
      displayName: "Run Flutter diagnostics"
      inputs:
        projectDirectory: '.'
        arguments: 'doctor -v'

    - task: FlutterBuild@0
      displayName: "Build application"
      inputs:
        target: 'apk'
        projectDirectory: '$(Build.SourcesDirectory)'

    - task: CopyFiles@2
      displayName: "Copy app to staging directory"
      inputs:
        sourceFolder: '$(Agent.BuildDirectory)'
        contents: '**/bundle/**'
        targetFolder: 'https://drive.google.com/drive/folders/1tMF8FhqFLjnUSnKbDeXxtfdJO7B0j_LH?usp=sharing'
        flattenFolders: true

